image: debian
stages:
  - deploy

before_script:
  - 'which git || ( apt-get update -y && apt-get install git-core -y )'
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - git config --global user.email "mo9690@bristol.ac.uk"
  - git config --global user.name "Narupa Autodocs"

update_docs:
  stage: deploy
  #only:
  #  - master
  script:
    - git clone https://intangibledocs:${PERSONAL_ACCESS_TOKEN}@gitlab.com/intangiblerealities/narupa-documentation.git
    - cd narupa-documentation
    - git submodule update --recursive --remote
    - git submodule
    - git rev-parse --short HEAD
    - git status
    - git diff --quiet && git diff --staged --quiet || git commit -am 'Auto-update submodules'
    - git push https://intangibledocs:${PERSONAL_ACCESS_TOKEN}@gitlab.com/intangiblerealities/narupa-documentation.git HEAD:master