image: debian
stages:
  - deploy

before_script:
  - 'which git || ( apt-get update -y && apt-get install git-core -y )'
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - git config --global user.email "mo9690@bristol.ac.uk"
  - git config --global user.name "Narupa Autodocs"

update_docs:
  stage: deploy
  #only:
  #  - master
  script:
    - git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com:intangiblerealities/narupa-documentation.git
    - cd narupa-documentation
    - cd narupa-protocol && git checkout master && git pull
    - git status
    - cd ..
    - git status
    - git add narupa-protocol && git commit -m 'Auto-update submodule'
    - git push http://intangibledocs:${PERSONAL_ACCESS_TOKEN}@gitlab.com:intangiblerealities/narupa-documentation.git HEAD:master