name: doc
channels:
  - omnia
  - conda-forge
  - defaults
dependencies:
  # As long as OpenMM is not compatible with python 3.8, solving the
  # environment is too expensive if the version of python is not specified.
  # This should be removed when OpenMM will be compatible with python 3.8.
  - python=3.7
  - MDAnalysis
  - openmm
